version: '3.8'

services:
  subletme_api:
    container_name: subletme_api
    image: subletme_api
    build:
      context: ./subletme_api
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_PORT: 443
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_USE_SSL: true
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_ENDPOINT_PUBLIC: ${MINIO_ENDPOINT_PUBLIC}
      API_BASE_URL: ${API_BASE_URL}
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT}
      VERSION_API_KEY: zPPxUvKrF3AotGgwXjLxykjRo&A6jUTKNqd
    ports:
      - "8082:8082"
      - "9229:9229"
    volumes:
      - ./subletme_api:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    depends_on:
      - subletme_db
      - minio

  subletme_db:
    container_name: subletme_db
    image: postgis/postgis:12-3.5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql
      - ./db/migrations:/migrations
    ports:
      - "5432:5432"

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Web Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
      MINIO_SERVER_URL: https://storage.submee.com
      MINIO_BROWSER_REDIRECT_URL: https://storage.submee.com

    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  db_data:
  minio_data:
