name: Deploy SubletMe

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Private Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build and push API image
      - name: Build and Push API
        uses: docker/build-push-action@v4
        with:
          context: ./subletme_api
          file: ./subletme_api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/subletme-api:latest
      
      - name: Trigger Portainer Webhook
        run: |
          curl -X POST https://portainer.thenush.net/api/stacks/webhooks/0d12c5db-0a0c-4531-84c9-683db35de277